### ISSUE TITLE
Unable to restore window after minimizing

### ISSUE THREAD

**Issue by Kiv** [Kiv/poclbm#1]
After minimizing the window to the notification area, it's not possible to restore the window.

Ubuntu 10.10 x64

**Comment by ghost** [comment]
Yep, confirmed. But you knew that already. :) Otherwise very awesome.

**Comment by impactdni** [comment]
Confirmed on 11.04 x86_64 as well. (Unity disabled)

**Comment by JurgenG** [comment]
Ubuntu 10.04 x64 (LTS) - same issue.
Great job!

**Comment by leovuonnala** [comment]
Same with Windows 7 64-bit. Otherwise, it's a great little program. 
E: If you delete the settings file from appdata/roaming/poclbm
Then it will start in windowed mode.

**Comment by rampa069** [comment]
i had the same problem (ubuntu X64) solved at my side.

 patch attached.

diff --git a/guiminer.py b/guiminer.py
index a4272b5..9c5dc57 100644
--- a/guiminer.py
+++ b/guiminer.py
@@ -1681,7 +1681,7 @@ class GUIMiner(wx.Frame):
         self.Bind(wx.EVT_MENU, self.on_change_language, id=ID_CHANGE_LANGUAGE)
         self.Bind(wx.EVT_MENU, self.on_donate, id=ID_DONATE_SMALL)
         self.Bind(wx.EVT_CLOSE, self.on_close)
-        self.Bind(wx.EVT_ICONIZE, lambda event: self.Hide())
-        self.Bind(wx.EVT_ICONIZE, lambda event: self.Show()) ##rampa
       self.Bind(fnb.EVT_FLATNOTEBOOK_PAGE_CLOSING, self.on_page_closing)
       self.Bind(fnb.EVT_FLATNOTEBOOK_PAGE_CLOSED, self.on_page_closed)
       self.Bind(fnb.EVT_FLATNOTEBOOK_PAGE_CHANGED, self.on_page_changed)

**Comment by JurgenG** [comment]
Great job!
Thanks for fixing that. :)

Works like a charm for me too.

Grtz,
Jurgen.

**Comment by Kiv** [comment]
Thanks, I'll integrate this in the next release.
