### ISSUE TITLE
Accidental donation to GUIminer

### ISSUE THREAD

**Issue by bVector** [Kiv/poclbm#115]
A friend of mine that I've introduced to bitcoin accidentally withdrew his mining rewards (0.25001386 BTC) to the donation address for @Kiv 

txid: b33b3140018a0537ab482685998f53c2902ab7c498cda37fe9a58917ad5ee370  

I'm not sure if this is the default withdrawl address for Slush's pool, or if my friend got confused with an address he saw somewhere, but it was silly and unintentional.

I know this is solely his fault, but I figured I'd reach out to see if there was any way to recover this accidental transaction. As this is his first ever experience with bitcoin, I'd like for it to be a positive one (and I'm sure he'll donate some as a thank you).  So I don't come across as a scammer, I'd suggest perhaps slush can verify the withdrawal was initiated by my friend and provide the corrected withdrawal address. Let me know if this is something someone could help with. 

Thanks, bV

**Comment by Kiv** [comment]
Ok, I see the transaction and I believe your story. No need to bother slush, post me the address and I'll send it over.

**Comment by bVector** [comment]
1BSr6rm52P4qTE1bpTgqkpUQtvwj18gmQr

Thanks again and sorry to have to bug you about this. :star2:
