### ISSUE TITLE
Slower performance with 6/14

### ISSUE THREAD

**Issue by ghost** [Kiv/poclbm#15]
Updated from 6/9 release and I lost nearly 80Mhash/s with OpenCL miner (HD5870 and -v -w128 -f60 flags). Normally get ~390Mhash/s, Im down near 310Mhash/s now. I re-did all settings and resetup from scratch, no change.

**Comment by Kiv** [comment]
I can't figure out what the problem is, but the new release later today will have a revamped OpenCL miner. You should actually see higher performance then the 6/9 release on the new one.

**Comment by ghost** [comment]
Oh wow, whatever the issue was it has been fixed. I see a 30Mhash/s increase from the 6/9 release! Excellent, Thanks!
