### ISSUE TITLE
CPU affinity on version 6/14

### ISSUE THREAD

**Issue by skynet2012** [Kiv/poclbm#16]
By default it uses all the cores. This becomes a problem with multiple miners, on a quad core/etc. It uses 25% cpu for each card 4*25=100 load. If I set it to use core 0 only then i get 25 % for all 4 cards. I think this feature would work better if was set to 1 core by default. Took me a few days to figure this out, but alot of people have not and are maxxing out their CPU for no good reason.

**Comment by Kiv** [comment]
Good idea. I set it to use only CPU #0 by default.
