### ISSUE TITLE
no GPU device

### ISSUE THREAD

**Issue by 0142929** [Kiv/poclbm#18]
**\* CAL version mismatch:
This OpenCL build requires version 1.4.879, version 1.4.635 installed.
Aborting.
No device specified or device not found, use -d to specify one of the following

[0]     Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz

---

---

i'm installed latest software, but ... there is no GPU

[hardware]
device: Sony VAIO VPCEA3S1R
video: ATI Mobility Radeon HD 5650
os: Windows 7 x86_64

[drivers]
latest video driver:
Graphics Driver (ATI) - 8.723.8.2 64 bits    229.12 MB   19/11/2010
http://www.sony.ru/product/vn-e-series/vpcea3s1r-w

latest OpenCL driver:
AMD APP SDK v2.4 with OpenCL™ 1.1
http://developer.amd.com/sdks/AMDAPPSDK/downloads/Pages/default.aspx

**Comment by 0142929** [comment]
in GUI: http://imageshack.us/photo/my-images/839/clipboard01kh.jpg
same error.

**Comment by Kiv** [comment]
I haven't seen that error before but from googling "CAL version mismatch" it looks like an driver issue and not specifically related to GUIMiner. 

Unfortunately I don't know anything about your card so I'm not sure if there's a specific driver version you need... maybe post on the forums and see if anyone has any ideas or has the same card as you.

**Comment by 0142929** [comment]
thanks
