### ISSUE TITLE
New address for slush pool

### ISSUE THREAD

**Issue by ToriAmos1963** [Kiv/poclbm#20]
It looks like there is a new address for slush to correct "connection" issues.

http://api2.bitcoin.cz:8332

It may be helpful to have the ability to change the address in the GUI.  It seems like this pool changes its address regularly after DDOS attacks.

Thanks,
Ali

**Comment by kenany** [comment]
Updated here: 336b9f7. Waiting for [pull request](https://github.com/Kiv/poclbm/pull/27) to go through.

**Comment by Kiv** [comment]
Thanks, this is updated in the new release.
