### ISSUE TITLE
There is no way to use a proxy

### ISSUE THREAD

**Issue by lgp1985** [Kiv/poclbm#24]
I'm behind a firewall and there is a squid proxy that I can use, but there is no configuration available to include address, port, username and password so it can connect through a proxy, as pools have http addresses.

**Comment by Kiv** [comment]
I'm not familiar with squid proxy so I don't know what it would take to support it. If this is something you could contribute then I would gladly accept a patch, otherwise I can put it on the "to do" list.

**Comment by lgp1985** [comment]
I'll try to help in sometime soon.

Enviado via iPhone

Em 18/07/2011, às 16:59, Kiv reply@reply.github.com escreveu:

**Comment by rampa069** [comment]
if you are using linux/unix. you can use proxychains.
