### ISSUE TITLE
A few things that may or may not help.

### ISSUE THREAD

**Issue by Mradr** [Kiv/poclbm#26]
I am no way a strong python master, and I know nothing about OpenCL, but I did notice some things in the code that could "help" over wall.... I did notice a lot of:

if bla = "": or if bla != 0:
why not just do:
if bla:

I saw a lot of .sleeps commands... seems like a waste if the program is to run as fast as it can.

Also, I am guessing you did test, but how are you gaining anything from threading the code? Wouldn't the python GIL get in the way? I think you are better of writing some timer code if you are just wanting you sync the code in the matter that way it is all one big thread instead of smaller threads fighting for control.

Another option would to also coverent some python code using cython. I've seen hug jumps in speed when I did with in my own server (not a bitcoin miner).

Take what I said with a grand of surger xD Like I said, I'm no way a geru of python, and I haven't read all the code to understand how it all works yet. The code other wise seems clean.

**Comment by Kiv** [comment]
If you're referring to the code in the poclbm backend, then you're in the wrong place :) I wrote only the GUI code and the poclbm code was written by m0mchil.

Since the miner backend code is completely bottlenecked by the GPU, I don't think it's really an issue what goes on in the CPU side. Typical CPU usage is less than 1% for this program.

**Comment by Mradr** [comment]
Oh, ok. Sorry :) What code (text file) is the bottnecked part then? I am trying to understand it all lol. OpenCL is still perty new to me, but I willing to take a look at it at least.

*Update, nvm I think I am understand now I've had more time to look at it. Yea I think I may know some ways to speed it up, but not much of speed up. Let me see if what I can get out of it.
