### ISSUE TITLE
New Server Support

### ISSUE THREAD

**Issue by Ketzer2002** [Kiv/poclbm#28]
Hi Kiv,

I've tried to Fork your Guiminer to support my Server. Unfortunately I didn't get the compilation of the Pythonfiles to work properly.

Everytime I'm trying to start the Guiminer it says:

Traceback (most recent call last):
  File "guiminer.py", line 14, in <module>
ImportError: No module named wx

its the import wx directive in guiminer.py that my eclipse doesn't understand... I now have 3 different Python Versions. 2.6, 2.7 and 3.2 and tried to use wx-28-ansi and unicode. none of them worked fine... do you know, how to solve this problem?

Thanks in Advance

Best Regards

Boris

By the way the guiminer.py in my Fork is allready updated to support my server, so If the solution for my problem is to complicated I would be happy, if you merge our versions and do an update of your software, so that my pool's api can be used.

For future upcoming pools it might be very usefull to set the different window settings (like if there is an api support or a withdrawal service) in a extra config file, or even in the servers.ini, so that you don't have to change guiminer.py everytime a pooladmin needs to support his features.

**Comment by Kiv** [comment]
Can you import wx from the Python interactive console? It seems like wx might not be on your path. You should see something like this:

C:\Users\Chris>python
Python 2.6.4 (r264:75708, Oct 26 2009, 08:23:19) [MSC v.1500 32 bit (Intel)] on
win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import wx
> > > wx.**version**
> > > '2.8.10.1'

**Comment by Ketzer2002** [comment]
it says:

> > > import wx
> > > wx.**version**
> > > '2.8.12.1'

so, there might be another problem, or should i use 2.8.10.1 version?

**Comment by Kiv** [comment]
I don't think the version is the problem, if you can get to it from the interactive console. It might be an issue with your Eclipse Pydev settings. Go to the "Interpreter - Python" section and make sure you have c:\python26\lib\site-packages\wx-2.8-msw-unicode on your System PYTHONPATH.

**Comment by Ketzer2002** [comment]
Hi Kiv,

thank you for the reply. I've tried to compile now with python 2.6 and it worked fine so far.

But there are some strange things happening. My compiled Guiminer doesn't ask for an api token... is there another module, that has to be fixed, so that the client asks for that. I tried different self.layoutsets in the guiminer for my server, but nothing changed... I see the button for "get balance", but no asking for an token... by the way there are many many modules missing in the compilation process, I have pyopencl installed completely, but he for example asks for pyopencl.Error the same is for numpy he just can't find all modules of it... I know that python has many weird settings to be done under windows, in order to work properly, but I never really tried it under windows... Maybe you can just merge my version into yours (its just 4 lines of code, so that my server works with "get balance"). I'll send you my first mined bitcoin as a donation for this task.

Best Regards

Boris

-----Ursprüngliche Nachricht-----
Von: Kiv [mailto:reply@reply.github.com] 
Gesendet: Freitag, 5. August 2011 03:35
An: Ketzer2002@gmx.de
Betreff: Re: [poclbm] New Server Support (#28)

I don't think the version is the problem, if you can get to it from the interactive console. It might be an issue with your Eclipse Pydev settings. Go to the "Interpreter - Python" section and make sure you have c:\python26\lib\site-packages\wx-2.8-msw-unicode on your System PYTHONPATH.

##

**Comment by Kiv** [comment]
Hey, not sure how you're doing with this but if you ever get it working send me a pull request and I'll review it.
