### ISSUE TITLE
2011-08-23 "Accepted" not working

### ISSUE THREAD

**Issue by CaringDev** [Kiv/poclbm#30]
With the latest 2011-08-23 release the "Accepted" column on the summary page seems broken (at least for slush/poclbm)
The pool actually accepts shares but they won't get listed.

**Comment by CaringDev** [comment]
Ah, it seems I now need to specify --verbose
Sorry for the noise.

**Comment by Kiv** [comment]
Thanks for writing this, I did make --verbose the default in 2011-08-24 to make things simple.

**Comment by CaringDev** [comment]
Thanks, I already installed this version. Works perfect. Any change that the _rejected_ will get listed on the summary page as well?
