### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by noonecares** [Kiv/poclbm#34]
Hi guys,

I noticed a Unicode Encode Error in guiminer. Iam just useing the newest Version (guiminer-20110824.exe).
What happened?
I entered my deepbit.net accountinformation and sayed "files->save". I also checked the "autostart"(checkbox) in the "summary" of this just entered new worker.
Then i closed the guiminer and want to start it again. The miner tries to load the saved settings and want to start automatically. The Problem is that i entered some strange ASCII codes for having a safe password. (containing i.e. #!?/_-ä)

Now?
I start the miner and get a error message: "error occured: see the logfile '***' for details"
here is the logfileentry:
Traceback (most recent call last):
  File "guiminer.py", line 2283, in <module>
  File "guiminer.py", line 2274, in run
  File "guiminer.py", line 1717, in **init**
  File "guiminer.py", line 1942, in load_config
  File "guiminer.py", line 955, in start_mining
  File "subprocess.pyo", line 621, in **init**
  File "subprocess.pyo", line 830, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 154: ordinal not in range(128)

best regards, noone

**Comment by Kiv** [comment]
Thanks for letting me know about this. I never tried it with non-ascii characters in the data, probably this will need some work to be supported. I can't promise when it will be fixed as things are very busy with me. 

If you know some programming or a friend that does I would welcome a patch for this.

**Comment by noonecares** [comment]
Hi,

y iam a developer and will have a look at it 
My problem now is that i cant use the. Guiminer it crashes immediately.
Can you explain me Where i can disable the autostart or delete my saved profile?
I couldnt find any file which changed or any regkey. 
I will try to fix this issue and give you a report.

Best regards, noone

Am 12.10.2011 um 04:18 schrieb Kiv reply@reply.github.com:

**Comment by Kiv** [comment]
Profile is in the AppData folder, which on my computer is here:

C:\Users\Chris\AppData\Roaming\poclbm\poclbm.ini

**Comment by noonecares** [comment]
oh great!
thank you i will have a look at this problem.

best regards.
