### ISSUE TITLE
Add a scheduling feature

### ISSUE THREAD

**Issue by edgeman16** [Kiv/poclbm#52]
My power is billed based on a time-of-use system. ie. my power is much cheaper overnight than it is during the day (half the price).
If GUIMiner could allow me to setup a simple schedule I could disable mining during weekdays and only mine weeknights/weekends and save quite a bit of money on my power bill.

**Comment by Kiv** [comment]
Are you using Windows? Windows has a task scheduler built in - I would look into that as a solution for you.

**Comment by edgeman16** [comment]
I am, and that's what I'm using (with the straight poclbm commandline instead of GUIMiner), it's just cumbersome setting up the schedule with it.
I think it involves 4 scheduled tasks (two for starting/stopping during the week, two for starting/stopping on weekends).
It took some putzing and I'm using the Sysinternals "pskill.exe" to kill the process when I want it to stop, so it's not exactly and easy solution.

I think it could be a nice feature of GUIMiner, but if it's out of scope/wontfix I'll close the issue.
