### ISSUE TITLE
ImportError: No module named tools

### ISSUE THREAD

**Issue by ghost** [Kiv/poclbm#57]
When I connect to slush's pool, I get the following error:

`ImportError: No module named tools`

It seems to be coming from `ioutil.py`  in this line:

`from serial.tools import list_ports`

I'm running Python 2.7.3 on Linux Mint Maya. I haven't installed python-opencl since I don't have any GPU or CUDA. (In fact, when GUIMiner starts it says "No OpenCL devices detected"). I have installed "python-serial" and "python-numpy" already. Meaning `import serial` works but `import serial.tools` fails.

This error happens with latest code from master (as of today).

**Comment by Calamitous** [comment]
I had this same problem on Ubuntu 12, this SO fixed it for me:

http://stackoverflow.com/questions/14108428/pyserial-no-module-named-tools

**Comment by avimar** [comment]
Yep, that fixed it for me too! I had to upgrade pyserial.

**Comment by Kiv** [comment]
Glad you guys were able to sort it out :)

**Comment by avimar** [comment]
Yes but since it's not just one person and non-obvious, could you put it in the docs somewhere with the list of dependencies?
