### ISSUE TITLE
Minor issue for new users mining locally

### ISSUE THREAD

**Issue by ToriAmos1963** [Kiv/poclbm#6]
Hi,

When you select "Launch Bitcoin as a server," the program immediately notifies the user that it's ready to work.  On my computers, it takes about 20 seconds before the Bitcoin server loads and creates connection.  If you try to mine before the client it ready, guiminer gives a connection error message.  Maybe the wording can be changed to tell the users to wait until the Bitcoin client is loaded and has connections.  Also, new users may not know about needing to wait until all the blocks are downloaded before mining.

The program is working beautifully.  I have it running on two computers, one with SLI.  They ally have Nvidia 9800 GT cards.  Each card is calculating 30 Mhash/sec.

I want to make a donation, but the link takes me to MyBitcoin site and I don't have any Bitcoins to send you right now.  Do you accept Paypal?

**Comment by Kiv** [comment]
That's a good point, I'll look into it when I get a chance. I'm glad the program is working out for you :)

I do accept PayPal, my address is ChrisM6794@gmail.com.

**Comment by ToriAmos1963** [comment]
You've got Paypal money!

One more thing I forgot to mention.  I couldn't get your program to work with BC version 0.3.22, but 0.3.21 seems to be working fine.

**Comment by Kiv** [comment]
Thanks for the donation :)

I had another person report an issue with 0.3.22, so I'm going to look into that today.

**Comment by ToriAmos1963** [comment]
I think the problem with with poclbm.

http://www.newslobster.com/random/how-to-get-started-using-your-gpu-to-mine-for-bitcoins-on-windows

**Comment by Kiv** [comment]
I updated the README about the solo mining issue, though I'm not sure how many are still solo mining at current difficulties.
