### ISSUE TITLE
guiminer doesn't work on windows 8 ?

### ISSUE THREAD

**Issue by xDEADC0DE** [Kiv/poclbm#63]
I've upgraded to windows 8 this morning, but now guiminer won't launch !

All I get is the icon in the taskbar for a few seconds, and it disapears. I have no error message, no windows, no error logs.

I have tried launching the app as an administrator, and in "windows xp" and "windows 7" compatibility modes.

**Comment by xDEADC0DE** [comment]
I even tried to launch it from the command line, no error message either, nothing is outputted to the console.

**Comment by Kiv** [comment]
That's very strange... unfortunately I don't have a Windows 8 machine to test on so I can't reproduce your issue at this time :(

**Comment by xDEADC0DE** [comment]
Is there a debug or verbose flag I could use ?

**Comment by Kiv** [comment]
No, but there could be a guiminer.log file created in the guiminer
directory. If there's nothing there then I'm really puzzled. Sadly I don't
know anything at all about Windows 8.

**Comment by xDEADC0DE** [comment]
Thanks, I guess something else is at work here... maybe some old setting ? I upgrade to windows 8, It's not a fresh install. i'll try erasing all the stored configuration.

**Comment by xDEADC0DE** [comment]
It works ! I upgraded my display drivers (ATI radeon 56-- HD) to the latest (beta) release.
