### ISSUE TITLE
rpcminer-cuda.exe?

### ISSUE THREAD

**Issue by pip010** [Kiv/poclbm#64]
where is it?
and why when starting CUDA I have nothing? nada!
no log, no error , no nothing :( 

ext path it is looking for it:
C:\Users\My.name\Downloads\guiminer-20121203\guiminer\miners\puddinpop\rpcminer-cuda.exe

i don't have folder miners !

**Comment by Elephant454** [comment]
I have the exact same problem. :(

**Comment by Kiv** [comment]
It's not supplied with current version because few people were using it... you can download the EXE separately and I think it will still work. Try: https://en.bitcoin.it/wiki/RPC_Miner
