### ISSUE TITLE
guiminer drops to khash

### ISSUE THREAD

**Issue by guardian419** [Kiv/poclbm#67]
Hello,

I have an issue.  I am running GUIminer with 2x  ATI 5970s.  The problem that I am having is that the Mhash rate will run for a few minutes at 300 mhash per core (1.2k mhash total) and then drop down to minimal (312 KHash) for no reason that I am able to troubleshoot.   Do you have any idea why this would be happening?

Any help would be appreciated.

Thank you

**Comment by otatma** [comment]
I have a similar issue.  I was running an ATI 5850 and my hashrate drops to ~100 khash regularly.  I have not tested the issue myself, but my searches suggest that the hashrate drop is linked to new blocks.

**Comment by Kiv** [comment]
If you're using the poclbm (OpenCL) backend, you'll need to bring it up on the poclbm tracker (https://github.com/m0mchil/poclbm), they might have seen your issue there. From what I can see it doesn't seem related to the GUI code specifically.
