### ISSUE TITLE
Add MTRed pool

### ISSUE THREAD

**Issue by chaud** [Kiv/poclbm#7]
```
    {
        "name": "MTRed",
        "host": "mtred.com",
        "url": "https://mtred.com/",
        "port": 8337,
        "balance_host": "https://mtred.com",
        "balance_url": "/api/user/key/%s/",
        "balance_token_url": "https://mtred.com/user/profile/edit.html"
    },
```

Not 100% sure that the balance will work, didn't look closely at the parsing code. My guess is it is something like changing confirmed to balance in the code, but you are the coder! An example of the JSON returned can be found at https://mtred.com/api/user/key/d0c3696e93e172c284fd1c818bee54b2 

Thanks!

**Comment by Kiv** [comment]
I couldn't get the balance to work and the example link you gave me also didn't work (just returned {"error":"Invalid Key"}). I'm going to add it without the balance feature for this release and maybe we'll get it working later.
