### ISSUE TITLE
Miner not connecting

### ISSUE THREAD

**Issue by orangecubenz** [Kiv/poclbm#93]
Hi there - been using for a few weeks now, and when I click start, it says connection problems under speed. It won't connect from there, and is the same on all 3 PC's i'm using on. I am using slush's pool. thanks for any help, i'm a total newb on mining (and to forums in general) so apologies if this is the wrong place for this.

**Comment by ashes1601** [comment]
i feel the same way i have no idea what i am doing i cant even figure out how to fill in the little liner screen thing help us

**Comment by orangecubenz** [comment]
I think you haven't signed up for a pool perhaps? My problem is that I was connecting and now can't. I took my PC to work and it's working fine there. I think my ISP has made changes. Actually, it's working at home now that I checked!

**Comment by clinton4** [comment]
Did you find a solution to the "connection problems" status? I am having same issue
